import { Router } from 'express';
import { getAllDRFs, getDRFAnalytics, getAttemptsByLead, createAttempt, approveAttempt, rejectAttempt, resetToPending, resendDRF, extendExpiry, reassignDRF, syncDRFEmails, deleteDRF } from '../controllers/oem.controller';
import { authenticate } from '../middleware/auth.middleware';
import { authorize } from '../middleware/role.middleware';

const router = Router();
router.use(authenticate);
router.get('/analytics',       authorize('admin', 'sales'),          getDRFAnalytics);
router.get('/',                authorize('admin', 'sales'),          getAllDRFs);
router.get('/lead/:leadId',    authorize('admin', 'sales'),          getAttemptsByLead);
router.post('/lead/:leadId',   authorize('admin', 'sales'),          createAttempt);
router.patch('/:id/approve',   authorize('admin'),                   approveAttempt);
router.patch('/:id/reject',    authorize('admin'),                   rejectAttempt);
router.patch('/:id/reset',     authorize('admin'),                   resetToPending);
router.post('/:id/resend',     authorize('admin', 'sales'),          resendDRF);
router.patch('/:id/extend',    authorize('admin'),                   extendExpiry);
router.patch('/:id/reassign',  authorize('admin'),                   reassignDRF);
router.post('/sync-emails',    authorize('admin', 'sales'),          syncDRFEmails);
router.delete('/:id',          authorize('admin', 'sales'),          deleteDRF);
export default router;
